### ISSUE TITLE
not compatible with bukkit economy

### ISSUE THREAD

**Issue by vaniron** [CloverCard/CloverSellItemToServer#1]
Hi, i tested your plugin with latest arclight and CMI + vault + economy bridge and it doesnt work. No errrors at all but gives money only to party (pixelmon) menu, /money showing no difference and after selling manually to npc the money gotten via previous command dissappear.

**Comment by CloverCard** [comment]
Got it. I'll into seeing how I can provide Spigot support for that.

**Comment by CloverCard** [comment]
After looking a bit into it, I found the primary source of troubles. After testing it with economy bridge, vault, and essentialsx, I got it supporting the economy functions.
